### ISSUE TITLE
pip Install Issue

### ISSUE THREAD

**Issue by WilliamJudge94** [mretegan/crispy#44] opened 2021-01-21 16:15 UTC
The crispy documentation says one needs to just use "pip3 install --upgrade crispy" to install. But one must install "silx" first since it is not apart of the pip module.

It would be much appreciated if the documentation or the pip install could be updated.

**Comment by mretegan** [comment] 2021-01-26 09:19
@WilliamJudge94 

There was indeed a problem with the 0.7.3 version of crispy. This is the one you when you run the "pip3 install --upgrade crispy". 

The issue is fixed in the pre-release version (2020.1rc0). To install this one run "pip3 install --upgrade crispy==2020.1rc0"

**Closed as completed** 2021-02-18 12:16 UTC
